# Generated by Django 6.1 on 2026-08-23 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Investment', 'Investment')], default='Expense', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recurring_frequency', models.CharField(choices=[('One-time', 'One-time'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('impact_level', models.CharField(choices=[('Low', 'Low Impact'), ('Medium', 'Medium Impact'), ('High', 'High Impact')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Finance', 'Financial Goal'), ('Study', 'Academic / Skill Goal'), ('Habit', 'Lifestyle & Fitness Goal')], default='Finance', max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('target_value', models.DecimalField(decimal_places=2, default=100.0, max_digits=12)),
                ('unit', models.CharField(default='$', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(choices=[('Sleep', 'Sleep Duration & Quality'), ('Workout', 'Workout / Physical Activity'), ('Meditation', 'Mindfulness & Meditation'), ('Hydration', 'Water Intake'), ('ScreenTime', 'Screen Time Limit')], max_length=50)),
                ('metric_value', models.CharField(help_text='e.g. 7.5 hrs, 5 km, 2.5 Liters', max_length=100)),
                ('consistency_score', models.IntegerField(default=80, help_text='Consistency score 1-100')),
                ('impact_level', models.CharField(default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('study_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('focus_rating', models.IntegerField(default=8, help_text='Rating out of 10')),
                ('key_takeaways', models.TextField(blank=True)),
                ('impact_level', models.CharField(default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(default='Software Engineer', max_length=120)),
                ('age', models.PositiveIntegerField(default=24)),
                ('bio', models.TextField(blank=True, default='Exploring personal optimization with AI Digital Twin.')),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12)),
                ('target_study_hours_weekly', models.DecimalField(decimal_places=1, default=20.0, max_digits=5)),
                ('goal_score', models.IntegerField(default=85, help_text='Calculated readiness score')),
                ('days_active', models.IntegerField(default=1)),
                ('avatar_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
