# Generated by Django 6.1 on 2026-09-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studyrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('Finance', 'Financial Objective'), ('Study', 'Academic / Skill Objective'), ('Habit', 'Lifestyle & Health Objective')], default='Finance', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='unit',
            field=models.CharField(default='₹', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='Digital Twin user exploring behavioral simulation.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal_score',
            field=models.IntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='DailyTelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True)),
                ('day_of_week', models.CharField(max_length=20)),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('food_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('travel_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shopping_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('utilities_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('health_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('work_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('study_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('screen_time_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('tasks_assigned', models.PositiveIntegerField(default=1)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('steps_count', models.PositiveIntegerField(default=5000)),
                ('exercise_duration_min', models.PositiveIntegerField(default=0)),
                ('sleep_hours', models.DecimalField(decimal_places=2, default=7.0, max_digits=4)),
                ('reading_meditation_min', models.PositiveIntegerField(default=0)),
                ('habit_completion_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stress_level', models.PositiveIntegerField(default=5)),
                ('mood_score', models.PositiveIntegerField(default=7)),
                ('behavioral_state', models.CharField(choices=[('Peak Focus', 'Peak Focus'), ('Burnout Risk', 'Burnout Risk'), ('Distracted', 'Distracted'), ('Recovery', 'Recovery')], default='Recovery', max_length=30)),
                ('next_day_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_day_productivity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date'],
                'unique_together': {('user', 'entry_date')},
            },
        ),
        migrations.DeleteModel(
            name='FinancialRecord',
        ),
        migrations.DeleteModel(
            name='HabitRecord',
        ),
        migrations.DeleteModel(
            name='StudyRecord',
        ),
    ]
