# Generated by Django 6.1 on 2026-09-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_userprofile_bio_financialrecord_habitrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=85000.0, max_digits=12),
        ),
    ]
